[
    {
      id: 1,
      name: 'Dimmer',
      dev_type: 'dimmer',
      groupDevice: 1,
    },
    {
      id: 2,
      name: 'Normor',
      dev_type: 'normor',
      groupDevice: 1,
    },
    {
      id: 3,
      name: 'Color',
      dev_type: 'color',
      groupDevice: 1,
    },
    {
      id: 5,
      name: 'rèm dọc',
      dev_type: 'ver_curtain',
      groupDevice: 2,
    },
    {
      id: 6,
      name: 'rèm ngang',
      dev_type: 'hor_curtain',
      groupDevice: 2,
    },
    {
      id: 7,
      name: 'rèm ngang phải',
      dev_type: 'hor_curtain_right',
      groupDevice: 2,
    },
    {
      id: 8,
      name: 'rèm ngang trái',
      dev_type: 'hor_curtain_left',
      groupDevice: 2,
    },
    {
      id: 9,
      name: 'Quạt',
      dev_type: 'desk_fan',
      groupDevice: 3,
    },
    {
      id: 10,
      name: 'Máy phun sương',
      dev_type: 'nebulizer',
      groupDevice: 3,
    },
    {
      id: 11,
      name: 'Máy lọc không khí',
      dev_type: 'air_purifier',
      groupDevice: 3,
    },
    {
      id: 12,
      name: 'Điều hòa',
      dev_type: 'normor_condition',
      groupDevice: 8,
    },
    {
      id: 13,
      name: 'Điều hòa cây',
      dev_type: 'plant_condition',
      groupDevice: 8,
    },
    {
      id: 14,
      name: 'Điều hòa âm trần',
      dev_type: 'cassette_condition',
      groupDevice: 8,
    },
    {
      id: 15,
      name: 'Loa bluetooth',
      dev_type: 'speaker',
      groupDevice: 9,
    },
    {
      id: 16,
      name: 'Ti vi',
      dev_type: 'tivi',
      groupDevice: 9,
    },
    {
      id: 17,
      name: 'cảm biến nhiệt độ, độ ẩm',
      dev_type: 'humidity_sensor',
      groupDevice: 10,
    },
    {
      id: 18,
      name: 'cảm biến hoạt động',
      dev_type: 'motion_sensor',
      groupDevice: 10,
    },
    {
      id: 19,
      name: 'Bình nóng lạnh',
      dev_type: 'water_heater',
      groupDevice: 7,
    },
    {
      id: 20,
      name: 'Máy hút mùi',
      dev_type: 'kitchen_hood',
      groupDevice: 7,
    },
    {
      id: 21,
      name: 'Máy hút bụi',
      dev_type: 'vacuum_cleaner',
      groupDevice: 7,
    },
    {
      id: 22,
      name: 'Máy giặt',
      dev_type: 'washing_machine',
      groupDevice: 7,
    },
    {
      id: 23,
      name: 'Tủ lạnh',
      dev_type: 'fridge',
      groupDevice: 7,
    },
    {
      id: 24,
      name: 'Cảnh báo cháy',
      dev_type: 'fire_alarm',
      groupDevice: 6,
    },
    {
      id: 25,
      name: 'bộ lọc',
      dev_type: 'membrane_filter_mid',
      groupDevice: 4,
    },
    {
      id: 26,
      name: 'Camera',
      dev_type: 'camera',
      groupDevice: 5,
    },
    {
      id: 27,
      name: 'Cửa hai  cánh',
      dev_type: 'balcony_door',
      groupDevice: 5,
    },
    {
      id: 28,
      name: 'Cửa một cánh',
      dev_type: 'main_door',
      groupDevice: 5,
    },
  ]